### ISSUE TITLE
Processing attachments

### ISSUE THREAD

**Issue by elsehow** [rasendubi/uniorg#18]
Thank you for this package!

When I write, I often include images with attachments. I am trying to use this library to convert `<img src="attachment:my-image.jpg">` to `<img src="my-image.jpg">`.

Does the library provide this functionality?

**Comment by rasendubi** [comment]
Do you mean using `org-attach` and `[[attachment:…]]` links? Uniorg does not offer this right now (or any link processing). However, it is possible to process URLs with [rehype-url-inspector](https://github.com/JS-DevTools/rehype-url-inspector).

e.g., `resolveLinks` in org-braindump example resolves `id:` and `file:` links: https://github.com/rasendubi/uniorg/blob/c1ee8de6e54693bf30dd95d065748d93ddf376e6/examples/org-braindump/src/lib/resolveLinks.js#L4-L63

To implement this in a general way, I would visit every link and if it’s an attachment, traverse up to a headline and see if it has `DIR` or `ID` property, then resolve the attachment path accordingly. [unist-util-visit-parents](https://www.npmjs.com/package/unist-util-visit-parents/v/4.1.1) might help here because it provides a list of ancestors.

**Comment by elsehow** [comment]
> Do you mean using org-attach and [[attachment:…]] links?

Exactly!

I tried the following, just to try to get a sense of what was going on:

```javascript
  if (url.protocol === 'attachment:') {
    node.properties[propertyName] = '';
  }
```

But to no avail. I still see HTML links like `src="attachment:undersea-cable-map.jpeg"`

I think my familiarity with the unified ecosystem isn't quite where it needs to be to implement what you describe, but it's exactly what I'm looking for. If you or someone else can implement this, I think it would be an extremely useful feature/workflow!

**Comment by rasendubi** [comment]
Where did your plug that code?

**Comment by elsehow** [comment]
I put it in `processUrl`: https://github.com/elsehow/else.how/blob/master/src/lib/processUrls.ts#L77-L79

**Comment by rasendubi** [comment]
Strange… it should have worked.

Anyway, I’ll try to implement a plugin to transform attachment links to file links when I have more spare time (hopefully, September). If you (or anyone else) want to implement this earlier, I can provide guidance.

**Comment by rasendubi** [comment]
Quick question. Do you use `org-attach-id-dir`?

>

**Comment by elsehow** [comment]
The variable is set (to `.attach` in my notes directory).

**Comment by rasendubi** [comment]
I have just published [`uniorg-attach`](https://www.npmjs.com/package/uniorg-attach) package to convert `attachment:` links to `file:` links.

It would be great if you could give it a try. Your code should look something like that:

```js
...
import { uniorgAttach } from 'uniorg-attach';
...

unified()
  .use(uniorgParse)
  .use(uniorgAttach, { idDir: '.attach' })
  .use(uniorg2rehype)
```

(Note that `uniorgAttach` must be used before `uniorg2rehype`.)
