### ISSUE TITLE
Extracting metadata from drawers

### ISSUE THREAD

**Issue by pard68** [rasendubi/uniorg#43]
It'd be great if all the metadata in a given drawer was exposed as data. For example, the :PROPERTIES: drawer often has valuable information that is useful for publishing (ie creation date, last edit date, file's status, etc.) and it is often used by other org-mode publishing utilities like org-publish, ox-huge, and lazyblorg. I do see that the drawers are exposed in post.values as raw data, but it'd be handy to maybe do something like

```
Vfile {
  data: {
    drawers: [
      properties: {
        id: "...",
        exported_date: "<...>",
        ...
     },
...```

**Comment by rasendubi** [comment]
I don't see much reason to do that for **all** drawers because drawer names are non-unique and position is important.

**Property** drawers are special though and can only occur at specific places so they are somewhat easier to find. For file-level properties, the property drawer is always the first item in `org-data`; for `section` (headlines), the property drawer is either second or third item (if `planning` is present).

It is possible to lift properties to the nearest parent but I would suggest doing that as a unified plugin. If you're interested in that, I am happy to help with guidance and/or accept the plugin to this repo.

**Comment by pard68** [comment]
Thanks, I'll check into that plugin route if/when I need to reach for that.
