### ISSUE TITLE
Support displayed math delimiters 

### ISSUE THREAD

**Issue by pokemaster7** [rasendubi/uniorg#7]
Math formulas delimited with `$$..$$` or with `\[..\]` are parsed as `latex-fragment` (inline) instead of `latex-environment` (displayed).

## Input:

```
$$E=mc^2$$
```
## Output:

```
<div>
<p><span class="math math-inline">E=mc^2</span></p>
</div>
```

## Expected Output:

```
<div>
<p><span class="math math-display">E=mc^2</span></p>
</div>
```

**Comment by rasendubi** [comment]
This is not a bug.

`$$E=mc^2$$` is a latex fragment according to [org syntax](https://orgmode.org/worg/dev/org-syntax.html). This is also how `org-element.el` parses the string:

```
$$E=mc^2$$
```
```
((section
  (:begin 1 :end 11 :contents-begin 1 :contents-end 11 :post-blank 0 :post-affiliated 1 :parent
          (org-data nil #1))
  (paragraph
   (:begin 1 :end 11 :contents-begin 1 :contents-end 11 :post-blank 0 :post-affiliated 1 :parent #1)
   (latex-fragment
    (:value "$$E=mc^2$$" :begin 1 :end 11 :post-blank 0 :parent #2)))))
```

**Comment by rasendubi** [comment]
The proper way to create display equations is to use `\begin{equation} … \end{equation}` or `\begin{equation*} … \end{equation*}`. That did not work before with katex because it did not support the `equation` environment [but it does now](https://github.com/KaTeX/KaTeX/pull/2369).

Works for me with rehype-katex@5.0.0 and katex@0.13.5.

Hope this helps
